2013-04-08 16:29:08,789:INFO: Error (<class '_mysql_exceptions.OperationalError'>) occurred in crawl.py, line 1154: (2003, "Can't connect to MySQL server on 'localhost' (10061)")
2013-04-08 16:29:08,789:INFO: Traceback:
2013-04-08 16:29:08,822:INFO: Traceback (most recent call last):
  File "E:\installs\Git\storage\GroceryOTG\Server\src\com\groceryotg\crawler\crawl.py", line 1154, in <module>
    con = mdb.connect('localhost', mysql_user, mysql_password, mysql_db, use_unicode=True, charset="utf8")
  File "E:\installs\Python27\lib\site-packages\MySQLdb\__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "E:\installs\Python27\lib\site-packages\MySQLdb\connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (2003, "Can't connect to MySQL server on 'localhost' (10061)")

